#!/usr/bin/env python3
"""
Closed-loop SITL validation of the VPE slew limiter on the survey13 flight.

The offline test (control/test_vpe_slew.py) proves what the *published* VPE
stream looks like; this test closes the loop through a real ArduPilot EKF3 +
position controller and shows what the aircraft actually FLIES.

Method
------
- ArduPilot SITL (builtin quad physics, no GPS, ExternalNav position source,
  EK3/PSC params mirroring control/real_hw.parm) takes off and is commanded
  along the survey13 GPS-truth route via GUIDED position setpoints.
- A 20 Hz vision feed sends VISION_POSITION_ESTIMATE = SITL true position +
  the *recorded* localizer error sequence from the survey13 replay logs
  (plan-B VO+AnyLoc track minus GPS truth — includes the AnyLoc jump /
  re-acquire teleports in the stress log).  This injects the exact error the
  real localizer produced, on top of whatever the SITL aircraft really does.
- `raw` mode publishes that estimate directly (current field behaviour);
  `slew` mode feeds it through control/vpe_slew.py first, dead-reckoned with
  the EKF velocity exactly as control/ardupilot_commander.py does.
- True position (SIMSTATE), EKF position and the VPE stream are logged.

Usage
-----
    python3 control/test_vpe_slew_sitl.py run stress raw
    python3 control/test_vpe_slew_sitl.py run stress slew
    python3 control/test_vpe_slew_sitl.py run normal raw
    python3 control/test_vpe_slew_sitl.py run normal slew
    python3 control/test_vpe_slew_sitl.py plot          # PNG from saved logs
    python3 control/test_vpe_slew_sitl.py all           # 4 runs + plot

Outputs: anyloc/logs/survey13_sitl_<scen>_<mode>.json and
         anyloc/logs/survey13_sitl_slew.png
"""

import json
import math
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, ROOT)

from vpe_slew import VpeSlewLimiter

ARDUCOPTER = os.path.join(ROOT, "third_party", "ardupilot",
                          "build", "sitl", "bin", "arducopter")
LOGS_DIR   = os.path.join(ROOT, "anyloc", "logs")
SCENARIOS  = {
    "stress": os.path.join(LOGS_DIR, "survey13_jumpgate_stress.json"),
    "normal": os.path.join(LOGS_DIR, "survey13_jumpgate_replay.json"),
    # synthetic OpenVINS-grade odometry + recorded AnyLoc candidates,
    # generated by control/gen_vio_track.py (real OpenVINS cannot run here:
    # SITL has no camera, survey13 recorded no high-rate IMU)
    "vio":    os.path.join(LOGS_DIR, "survey13_vio_synth.json"),
}
TRACK      = "new"          # plan-B VO+AnyLoc policy track
HOME_ALT   = 28.0           # m MSL, arbitrary
M_PER_DEG  = 111_320.0
TICK_S     = 0.05           # 20 Hz vision feed (commander cadence)
SETP_S     = 0.2            # 5 Hz GUIDED position setpoints
HOLD_S     = 5.0            # hover hold after the route ends
# SERIAL0 (5760): SITL blocks at boot until a client connects here, so the
# harness must use this port, not 5762.
CONNECT    = "tcp:127.0.0.1:5760"

# Commander covariance for a good estimate: cov_xy = max(1, err²) → 1 m²
VPE_COV = [1.0, 0, 0,    0,    0,    0,
                1.0, 0,  0,    0,    0,
                     0.25, 0,  0,    0,
                           0.09, 0,  0,
                                 0.09, 0,
                                       0.09]

# EK3/PSC/failsafe setup mirroring control/real_hw.parm (SRC2 there = SRC1
# here — SITL boots straight into the vision source set), GPS fully disabled.
SITL_PARAMS = {
    "AHRS_EKF_TYPE":   3,
    "FRAME_CLASS":     1,
    "FRAME_TYPE":      1,
    "GPS_TYPE":        0,      # pre-4.7 name — harmless if unknown
    "GPS1_TYPE":       0,
    "SIM_GPS_DISABLE": 1,
    "SIM_GPS1_ENABLE": 0,
    "EK3_SRC1_POSXY":  6,      # ExternalNav position
    "EK3_SRC1_VELXY":  0,      # no velocity source — matches real_hw.parm
    "EK3_SRC1_POSZ":   1,      # baro
    "EK3_SRC1_VELZ":   0,      # default is GPS → trips "sources require GPS"
    "EK3_SRC1_YAW":    1,      # compass
    "VISO_TYPE":       1,
    "EK3_GLITCH_RAD":  50,     # matches real_hw.parm
    "PSC_NE_POS_P":    0.2,    # real_hw.parm position controller
    "PSC_NE_VEL_P":    2.0,
    "PSC_NE_VEL_I":    0.0,
    "PSC_NE_VEL_D":    0.5,
    "WPNAV_SPEED":     1200,
    "WPNAV_SPEED_UP":  300,
    "ARMING_CHECK":    0,
    "GPS_ARMING_MIN_SAT": 0,
    "FS_GPS_ENABLE":   0,
    "FS_EKF_THRESH":   1.0,    # most relaxed — we *want* to watch the runaway
    "FS_CRASH_CHECK":  0,
    "FENCE_ENABLE":    0,
    "DISARM_DELAY":    0,
    "GUID_TIMEOUT":    30,
    "LOG_BACKEND_TYPE": 0,     # no dataflash logs in the scratch dir
}


# ── survey13 data ─────────────────────────────────────────────────────────────
def load_scenario(path):
    """Returns (t0-based times, truth interp fn, err fn, agl, gps0, cos_lat)."""
    with open(path) as f:
        d = json.load(f)
    lat0, lon0 = d["gps0"]
    cos_lat = d["cos_lat"]
    rows = d["rows"]
    ts  = [r["t"] for r in rows]
    tru = [((r["true_lon"] - lon0) * M_PER_DEG * cos_lat,
            (r["true_lat"] - lat0) * M_PER_DEG) for r in rows]
    trk = [((r[f"{TRACK}_lon"] - lon0) * M_PER_DEG * cos_lat,
            (r[f"{TRACK}_lat"] - lat0) * M_PER_DEG) for r in rows]
    agl = sum(r["agl"] for r in rows) / len(rows)

    # truth is piecewise-constant at telemetry rate → interpolate its changes
    ch  = [0] + [k for k in range(1, len(tru)) if tru[k] != tru[k - 1]]
    cts = [ts[k] for k in ch]
    cen = [tru[k] for k in ch]

    def truth_at(t):
        if t <= cts[0]:
            return cen[0]
        if t >= cts[-1]:
            return cen[-1]
        lo, hi = 0, len(cts) - 1
        while hi - lo > 1:
            mid = (lo + hi) // 2
            if cts[mid] <= t:
                lo = mid
            else:
                hi = mid
        a = (t - cts[lo]) / (cts[hi] - cts[lo])
        return (cen[lo][0] + a * (cen[hi][0] - cen[lo][0]),
                cen[lo][1] + a * (cen[hi][1] - cen[lo][1]))

    def err_at(t):
        """Recorded localizer error (E, N) at replay time t (latest row ≤ t)."""
        lo, hi = 0, len(ts) - 1
        while hi - lo > 1:
            mid = (lo + hi) // 2
            if ts[mid] <= t:
                lo = mid
            else:
                hi = mid
        te, tn = truth_at(t)
        return trk[lo][0] - te, trk[lo][1] - tn

    return ts[-1], truth_at, err_at, agl, (lat0, lon0), cos_lat


# ── SITL flight ───────────────────────────────────────────────────────────────
def run_flight(scenario: str, mode: str):
    from mavlink_ctrl import MAVLinkCtrl
    from pymavlink import mavutil

    span, truth_at, err_at, agl, (lat0, lon0), _ = \
        load_scenario(SCENARIOS[scenario])
    print(f"[SITL-test] {scenario}/{mode}: route {span:.0f} s, AGL {agl:.0f} m")

    workdir = os.path.join(os.environ.get("TMPDIR", "/tmp"),
                           f"vpe_slew_sitl_{scenario}_{mode}")
    os.makedirs(workdir, exist_ok=True)
    parm = os.path.join(workdir, "test.parm")
    with open(parm, "w") as f:
        for k, v in SITL_PARAMS.items():
            f.write(f"{k} {v}\n")

    proc = subprocess.Popen(
        [ARDUCOPTER, "--model", "quad", "--speedup", "1",
         "--defaults", parm, "--home", f"{lat0},{lon0},{HOME_ALT},0", "-I0"],
        cwd=workdir, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
    time.sleep(4)

    log = dict(scenario=scenario, mode=mode, agl=agl, rows=[])
    try:
        ctrl = MAVLinkCtrl(CONNECT)
        if not ctrl.wait_heartbeat(30):
            raise RuntimeError("no heartbeat from SITL")
        mav = ctrl._mav
        for msg_id, hz in ((mavutil.mavlink.MAVLINK_MSG_ID_SIMSTATE, 25),
                           (mavutil.mavlink.MAVLINK_MSG_ID_LOCAL_POSITION_NED, 25)):
            mav.mav.command_long_send(
                mav.target_system, mav.target_component,
                mavutil.mavlink.MAV_CMD_SET_MESSAGE_INTERVAL, 0,
                msg_id, int(1e6 / hz), 0, 0, 0, 0, 0)

        ctrl.set_ekf_origin(lat0, lon0, HOME_ALT)
        ctrl.set_home_position(lat0, lon0, HOME_ALT)

        slew = VpeSlewLimiter() if mode == "slew" else None

        def sim_truth_en():
            m = mav.messages.get("SIMSTATE")
            if m is None:
                return None
            la, lo_ = m.lat, m.lng
            if abs(la) > 1000:          # int degE7 encoding
                la, lo_ = la / 1e7, lo_ / 1e7
            return ((lo_ - lon0) * M_PER_DEG * math.cos(math.radians(lat0)),
                    (la - lat0) * M_PER_DEG)

        def vpe_tick(route_t=None):
            """One 20 Hz vision tick; returns published (e, n) or None."""
            te_n = sim_truth_en()
            if te_n is None:
                return None
            te, tn = te_n
            if route_t is None:
                ee, en = 0.0, 0.0         # perfect vision before the route
            else:
                ee, en = err_at(route_t)
            tgt_e, tgt_n = te + ee, tn + en
            if slew is not None:
                pe, pn = slew.update(tgt_e, tgt_n, time.monotonic())
            else:
                pe, pn = tgt_e, tgt_n
            lp = ctrl.local_pos
            down = lp.z if lp is not None else 0.0
            ctrl.send_vision_position(pn, pe, down, 0.0, VPE_COV)
            if route_t is not None:
                log["rows"].append(dict(
                    t=round(route_t, 3),
                    truth=[round(te, 2), round(tn, 2)],
                    ekf=[round(lp.y, 2), round(lp.x, 2)] if lp else None,
                    est=[round(tgt_e, 2), round(tgt_n, 2)],
                    pub=[round(pe, 2), round(pn, 2)]))
            return pe, pn

        def pump(duration=None, cond=None, route_start=None, timeout=180):
            t_end = time.monotonic() + (duration if duration else timeout)
            next_vpe = next_sp = 0.0
            while time.monotonic() < t_end:
                now = time.monotonic()
                ctrl.recv()
                if now >= next_vpe:
                    rt = (now - route_start) if route_start else None
                    if rt is not None and rt > span:
                        rt = span
                    vpe_tick(rt)
                    next_vpe = now + TICK_S
                if route_start and now >= next_sp:
                    rt = min(now - route_start, span)
                    re, rn = truth_at(rt)
                    ctrl.set_position_ned(rn, re, -agl)
                    next_sp = now + SETP_S
                if cond is not None and cond():
                    return True
                time.sleep(0.005)
            return duration is not None    # timed pumps always "succeed"

        # EKF needs origin + steady VPE before it reports a position
        print("[SITL-test] waiting for EKF position…")
        if not pump(cond=lambda: ctrl.ekf_pos_valid, timeout=90):
            raise RuntimeError("EKF never got a position fix")
        pump(duration=5)                  # let the filter settle

        # Origin sent right after boot can be dropped while the EKF is still
        # aligning, and home ("Arm: AHRS: waiting for home") needs the origin
        # plus a DO_SET_HOME command (SET_HOME_POSITION is ignored on ≥4.x).
        # Retry both until ArduPilot broadcasts the confirmations.
        for _ in range(10):
            if "GPS_GLOBAL_ORIGIN" not in mav.messages:
                ctrl.set_ekf_origin(lat0, lon0, HOME_ALT)
            else:
                mav.mav.command_long_send(
                    mav.target_system, mav.target_component,
                    mavutil.mavlink.MAV_CMD_DO_SET_HOME, 0,
                    0, 0, 0, 0, lat0, lon0, HOME_ALT)
            pump(duration=1)
            if "HOME_POSITION" in mav.messages:
                break
        else:
            raise RuntimeError("origin/home never accepted")

        ekf = mav.messages.get("EKF_STATUS_REPORT")
        print(f"[SITL-test] pre-arm: ekf_flags="
              f"{ekf.flags if ekf else '?'} "
              f"origin={'GPS_GLOBAL_ORIGIN' in mav.messages} "
              f"home={'HOME_POSITION' in mav.messages} "
              f"set_home_ack={ctrl._last_ack.get(179)}")

        ctrl.set_mode("GUIDED")
        pump(duration=1)
        for attempt in range(3):
            ctrl.arm(force=True)
            pump(duration=3)
            if ctrl.is_armed:
                break
            st = mav.messages.get("STATUSTEXT")
            hb = mav.messages.get("HEARTBEAT")
            print(f"[SITL-test] arm attempt {attempt + 1} failed; "
                  f"ack={ctrl._last_ack.get(400)} "
                  f"mode={hb.custom_mode if hb else '?'} "
                  f"statustext={st.text if st else '-'}")
        if not ctrl.is_armed:
            raise RuntimeError("arm failed")
        ctrl.takeoff(agl)
        print(f"[SITL-test] climbing to {agl:.0f} m…")
        lp_alt = lambda: (ctrl.local_pos is not None
                          and -ctrl.local_pos.z > agl - 2.0)
        if not pump(cond=lp_alt, timeout=90):
            raise RuntimeError("takeoff did not reach altitude")
        pump(duration=3)

        print(f"[SITL-test] flying survey13 route with {mode} VPE injection…")
        pump(duration=span + HOLD_S, route_start=time.monotonic())
        print("[SITL-test] route done")
    finally:
        proc.terminate()
        try:
            proc.wait(5)
        except subprocess.TimeoutExpired:
            proc.kill()

    out = os.path.join(LOGS_DIR, f"survey13_sitl_{scenario}_{mode}.json")
    with open(out, "w") as f:
        json.dump(log, f)
    n = len(log["rows"])
    print(f"[SITL-test] {n} samples → {out}")
    return out


# ── plots ─────────────────────────────────────────────────────────────────────
def dist_to_polyline(p, pts):
    """Min distance from point p to the polyline pts (cross-track error —
    unlike distance to the commanded point at time t, this excludes the
    ordinary along-track controller lag)."""
    best = float("inf")
    px, py = p
    for (ax, ay), (bx, by) in zip(pts, pts[1:]):
        dx, dy = bx - ax, by - ay
        L2 = dx * dx + dy * dy
        u = 0.0 if L2 == 0 else max(0.0, min(1.0,
            ((px - ax) * dx + (py - ay) * dy) / L2))
        best = min(best, math.hypot(px - (ax + u * dx), py - (ay + u * dy)))
    return best


def plot():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    scens = [s for s in SCENARIOS
             if any(os.path.exists(os.path.join(
                 LOGS_DIR, f"survey13_sitl_{s}_{m}.json"))
                 for m in ("raw", "slew"))]
    fig, axes = plt.subplots(2, len(scens), squeeze=False,
                             figsize=(7.5 * len(scens), 11))
    for col, scen in enumerate(scens):
        span, truth_at, _, _, _, _ = load_scenario(SCENARIOS[scen])
        route = [truth_at(t) for t in
                 [i * 0.2 for i in range(int(span / 0.2) + 1)]]
        ax, axd = axes[0][col], axes[1][col]
        ax.plot([p[0] for p in route], [p[1] for p in route],
                "k--", lw=1.5, label="commanded route (survey13 GPS truth)")
        for mode, color in (("raw", "tab:red"), ("slew", "tab:green")):
            path = os.path.join(LOGS_DIR, f"survey13_sitl_{scen}_{mode}.json")
            if not os.path.exists(path):
                continue
            with open(path) as f:
                rows = json.load(f)["rows"]
            ax.plot([r["truth"][0] for r in rows],
                    [r["truth"][1] for r in rows],
                    color=color, lw=1.8, label=f"flown ({mode} VPE)")
            dev = [(r["t"], dist_to_polyline(r["truth"], route))
                   for r in rows]
            axd.plot([d[0] for d in dev], [d[1] for d in dev],
                     color=color, lw=1.5, label=f"{mode} VPE")
        gate = SCENARIOS[scen]
        with open(gate) as f:
            g = json.load(f)["params"]["gate"]
        ax.set_title(f"{scen} error track (gate {g:g}"
                     + (", teleports)" if scen == "stress" else ")"))
        ax.set_xlabel("East [m]"); ax.set_ylabel("North [m]")
        ax.axis("equal"); ax.grid(alpha=0.3); ax.legend(fontsize=9)
        axd.set_title("cross-track distance from commanded route")
        axd.set_xlabel("route time [s]"); axd.set_ylabel("deviation [m]")
        axd.grid(alpha=0.3); axd.legend(fontsize=9)
    fig.suptitle("SITL closed-loop: survey13 VO+AnyLoc error injection — "
                 "raw vs slew-limited VPE", fontsize=13)
    fig.tight_layout()
    out = os.path.join(LOGS_DIR, "survey13_sitl_slew.png")
    fig.savefig(out, dpi=110)
    print(f"[SITL-test] plot → {out}")
    return out


def main():
    args = sys.argv[1:]
    if args[:1] == ["run"] and len(args) == 3:
        run_flight(args[1], args[2])
    elif args[:1] == ["plot"]:
        plot()
    elif args[:1] == ["all"]:
        for scen in ("stress", "normal"):
            for mode in ("raw", "slew"):
                run_flight(scen, mode)
        plot()
    else:
        print(__doc__)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
